### ISSUE TITLE
How to use this tool to deobfuscator a il2cpp apk step by step? plz

### ISSUE THREAD

**Issue by ratsafalig** [OsOmE1/Beebyte-Deobfuscator#10]
Assume I now have a il2cpp with beebyte obfuscated APK file, and I try to open it with il2cpp-inspector.
I don't know anything about how beebyte work at all.

And the il2cpp-inspector require me to input beebyte-naming-scheme and a unobfuscated APK (that's what is says on the tab)
![image](https://user-images.githubusercontent.com/33503055/121624915-065b6680-caa5-11eb-82e4-4af5836ad909.png)

- Can I ask what is beebyte-naming-scheme and how can I find it
- What is it means by `unobfuscated GameAssembly.dll or Package` ? does that mean "if I want to unobfuscated a APK, I must first have an unobfuscated APK?"

**Comment by ratsafalig** [comment]
sorry for didn't read `readme` properly, you do need a unobfuscated file of it

**Comment by ratsafalig** [comment]
But this lead me to another confusion. Why do you need to unobfuscated if you already have a unobfuscated game?
And also, can you help me understanding what is naming scheme of beebyte
thanks, thanks, thanks

**Comment by OsOmE1** [comment]
Everything is in the readme. I also do not understand a word you wrote please use correct English.
