### ISSUE TITLE
Is there version for not IL2CPP?

### ISSUE THREAD

**Issue by Darkar25** [OsOmE1/Beebyte-Deobfuscator#11]
either im dumb or IL2CPPInspector cant open non-IL2CPP dlls...i have less-obfuscated and obfuscated dll files but i cant use your deobfuscator because i dont know how to pass obfuscated dll to IL2CPPInspector...
so, is there any version for normal dlls so i don`t need to rewrite your deobfuscator on ILSpy.Decompiler library?

**Comment by OsOmE1** [comment]
First off what you call "normal dlls" are managed dlls. Then to answer your question no this deobfuscator does not work with only managed dlls.
