### ISSUE TITLE
Add nameTranslation.txt support

### ISSUE THREAD

**Issue by LADIlib** [OsOmE1/Beebyte-Deobfuscator#14]
BeeByte has nameTranslation.txt on a dev builds. Please add nameTranslation.txt support(i can supply with all needed stuff)

**Comment by SliceCast** [comment]
You have discord?

**Comment by LADIlib** [comment]
> You have discord?

Yes, i have

**Comment by SliceCast** [comment]
Add me SliceCast#5648

**Comment by OsOmE1** [comment]
I'd suggest making your own Il2CppInspector plugin for this

**Comment by LADIlib** [comment]
> I'd suggest making your own Il2CppInspector plugin for this

I've tried, but no result (
Plugin just dont translate anything

**Comment by LADIlib** [comment]
> Add me SliceCast#5648

added

**Comment by OsOmE1** [comment]
[TranslationsLoader](https://github.com/OsOmE1/TranslationsLoader)

**Comment by LADIlib** [comment]
> [TranslationsLoader](https://github.com/OsOmE1/TranslationsLoader)

some still obfuscated 

	private void OnPlayerTimeNotify(Proto.PlayerTimeNotify GNDNGJLMLAM, MoleMole.Packet LFGIBPOCOAP);
	private void OnServerTimeNotify(Proto.ServerTimeNotify GNDNGJLMLAM, MoleMole.Packet LFGIBPOCOAP);
	private void OnSceneTimeNotify(Proto.SceneTimeNotify GNDNGJLMLAM, MoleMole.Packet LFGIBPOCOAP);

**Comment by LADIlib** [comment]
> [TranslationsLoader](https://github.com/OsOmE1/TranslationsLoader)

#ReverseOrder
#Classes
#Methods
#Fields
#Properties
#Events
#Parameters

Obfuscation parameters
