### ISSUE TITLE
How do you use this plugin?

### ISSUE THREAD

**Issue by wafflethings** [OsOmE1/Beebyte-Deobfuscator#2]

**Comment by wafflethings** [comment]
Nevermind I'm dumb.

**Comment by wafflethings** [comment]
Nevermind, I downloaded the release, put it into the folder but it shows nothing.

**Comment by OsOmE1** [comment]
It should be the folder and not only the dll.

**Comment by wafflethings** [comment]
Nevermind, had an outdated Il2CppInspector. Built one and it works fine
