### ISSUE TITLE
No output.

### ISSUE THREAD

**Issue by wafflethings** [OsOmE1/Beebyte-Deobfuscator#3]
Title. I set everything in the options - the GameAssembly to the game's GameAssembly, etc but nothing exports.

**Comment by OsOmE1** [comment]
Please provide more information.
What game?
What settings?

**Comment by wafflethings** [comment]
The game's Among Us, itch.io version.
Settings:
![image](https://user-images.githubusercontent.com/60797216/105351301-4b5d2a00-5be4-11eb-9830-ea469d971365.png)

**Comment by OsOmE1** [comment]
please attach the GameAssembly and Metadata file

**Comment by wafflethings** [comment]
[Among Us.zip](https://github.com/OsOmE1/Beebyte-Deobfusctator/files/5849448/Among.Us.zip)

**Comment by wafflethings** [comment]
That zip has the GameAssembly and global-metadata.

**Comment by OsOmE1** [comment]
@wafflethings what part of **unobfuscated** do you not understand
![image](https://user-images.githubusercontent.com/35796520/105363656-92efb000-5bfc-11eb-8e66-0327c111dcf7.png)
