### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sf2assets** [OsOmE1/Beebyte-Deobfuscator#4]
Hey it's giving this: 
![ssswww](https://user-images.githubusercontent.com/77153478/106009609-920dc100-60c9-11eb-897e-71c46cf235d6.png)

**Comment by OsOmE1** [comment]
Please provide more information

**Comment by sf2assets** [comment]
> Please provide more information

I'm trying to deobfuscate game called Shadow Fight 2. It has the beebyte obfuscation.
What is path to un-obfuscated option? Which path i need to setup?

**Comment by OsOmE1** [comment]
To use this plugin you need an un-obfuscated version of the game

**Comment by sf2assets** [comment]
> To use this plugin you need an un-obfuscated version of the game

it hasn't got it.  After they changed game engine from Marmalade to Unity they obfuscated everything.

**Comment by OsOmE1** [comment]
Then you cannot use this plugin
