### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by SyDant** [OsOmE1/Beebyte-Deobfuscator#5]
error while executing PostProcessTypeModel: Cross compiler deobfuscation
![image](https://user-images.githubusercontent.com/31112169/107734813-ddaea480-6d30-11eb-9a46-eecac83761ca.png)

**Comment by OsOmE1** [comment]
@shikitemeikato please stick to the bug report template I can't help you with this little information.

**Comment by OsOmE1** [comment]
Closing issue due to no response.
