### ISSUE TITLE
How can I find the BeeByte naming scheme on this file?

### ISSUE THREAD

**Issue by LainFan43462** [OsOmE1/Beebyte-Deobfuscator#6]
I should be looking for it in the obfuscated GameAssembly, right? 
I don't really know where to start looking. 
![image](https://user-images.githubusercontent.com/84733950/119382305-3aa6e880-bc98-11eb-895a-6ebfd980556c.png)
This is the file in question
[Assembly-CSharp.zip](https://github.com/OsOmE1/Beebyte-Deobfuscator/files/6533853/Assembly-CSharp.zip)
Sorry for the noob question, this is the first time I've tried to modify a unity game.

**Comment by OsOmE1** [comment]
This one looks to have the default configuration aka the same as listed under among us in the readme

**Comment by OsOmE1** [comment]
As for how you can find it, make sure to open the root namespace marked with -

**Comment by LainFan43462** [comment]
Hey, thanks so much for the answer! I'm not sure if it's proper GitHub etiquette to open a new thread when faced with a separate error, but as to not flood the issues section I decided to post the follow-up here. If that's not fine then please feel free to close it and I'll repost. 

Whenever I drop the obfuscated APK into the il2cpp inspector, this plugin error pops up:
![image](https://user-images.githubusercontent.com/84733950/120114213-72a8a280-c154-11eb-8ffd-7b48bce8be16.png)

This is the configuration I have set up for the deobfuscator: 
![image](https://user-images.githubusercontent.com/84733950/120114256-b13e5d00-c154-11eb-9e85-bd031817c2f9.png)

Perhaps I'm doing something wrong, or misunderstanding the purpose of the tool. I'd really appreciate your help. Thanks!

**Comment by OsOmE1** [comment]
"It's common for mobile games to be compiled with the gcc compiler while msvc is used for windows this causes compatibility issues so you cannot use this plugin across compilers." That's what's in the readme you can only use the following combination. APK with APK, dll with dll and dll with mono.
