### ISSUE TITLE
How i find regex? my game is block strike (android)

### ISSUE THREAD

**Issue by IroniaTheMaster** [OsOmE1/Beebyte-Deobfuscator#8]
He have Beebyte obfuscator, i dont know beebyte deofuscator work...
![Screenshot_2](https://user-images.githubusercontent.com/70151358/119717280-7aa6d080-be3c-11eb-88be-6e6720fb99b4.png)

**Comment by OsOmE1** [comment]
Please read the readme and follow the instructions. As to how to find the pattern you can refer to #6
