### ISSUE TITLE
GameAssembly.dll is libil2cpp.so for games or it's other thing ?

### ISSUE THREAD

**Issue by MhmRdd** [OsOmE1/Beebyte-Deobfuscator#9]
Well i wanted to know about this , is GamsAssembly.dll the C++ File compiled or APK or a game ressource , and where to find it ? and how to know if it's obfusctaed ?

**Comment by OsOmE1** [comment]
Yes, the GameAssembly.dll is for windows only and is often compiled with the MSVC compiler(not always). libil2cpp.so is included in APK's and is almost always an ELF binary compiled with the GCC compiler. You can see if it's obfuscated by looking at the output of Il2CppInspector. It will also show you if the Beebyte namespace is present if it is you'll be able to see if Beebyte was used to obfuscate the program. Also, please note that any questions about Il2Cpp technicalities do not belong in this issue section but rather on a forum or in Il2CppInspector's issue section.
